### ISSUE TITLE
Modify Java bindings to use C bindings

### ISSUE THREAD

**Issue by jrhea** [prrkl/mothra#19]
There is overlap between JNI and C bindings and the code should be consolidated.

**Comment by sgryphon** [comment]
The C-bindings, use in the C and dotnet examples simply allow a handler to be registered, and then forwards (peer, received, etc) events to those handlers. This could be used by the Java example (compile against the C-bindings, define the interop handler, call register handler).

**Comment by sgryphon** [comment]
Once this is done, you probably don't need the ingress library at all. The libp2p_register... function in Rust could just store the handler references, and then call them directly when the events occur.
